export enum AdminEnum {
  DEACTIVATED_USER = 'AdminEnum',
  ADMIN_LOGGED_IN = 'ADMIN_LOGGED_IN',
  ADMIN_NOT_EXIST = 'ADMIN_NOT_EXIST',
  PLEASE_USE_VALID_PASSWORD = 'PLEASE_USE_VALID_PASSWORD',
  ACCOUNT_NOT_EXIST = 'PLEASE_USE_VALID_PASSWORD',
  RESET_PASSWORD_MAIL = 'PLEASE_USE_VALID_PASSWORD',
  INVALID_OTP = 'PLEASE_USE_VALID_PASSWORD',
  VERIFICATION_COMPLETED = 'PLEASE_USE_VALID_PASSWORD',
  OTP_RESEND = 'PLEASE_USE_VALID_PASSWORD',
  USER_NOT_FOUND = 'PLEASE_USE_VALID_PASSWORD',
  OLD_PASSWORD_SAME = 'OLD_PASSWORD_SAME',
  OTP_NOT_VERIFY = 'OTP_NOT_VERIFY',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  RESET_PASSWORD = 'RESET_PASSWORD',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  YOU_ENTER_WRONG_PASSWORD = 'YOU_ENTER_WRONG_PASSWORD',
  DATA_GET = 'DATA_GET',
  ADMIN_UPDATED = 'ADMIN_UPDATED',
  ADMIN_LOGOUT = 'ADMIN_LOGOUT',
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ADMIN_ROLE = 'ADMIN_ROLE',
}

export enum userWalletTypeEnum {
  WEB3MODEL = 'web3model',
  MAGIC = 'magic',
}

export enum userRegisterTypeEnum {
  OTP = 'OTP',
  PASSWORD = 'Password',
}
