export enum TransactionEnum {
  GET_DEPOSIT_AMOUNT = 'GET_DEPOSIT_AMOUNT',
  TRANSITION_NOT_FOUND = 'TRANSITION_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_GET = 'TRANSACTION_GET',
  TRANSITION_CREATED = 'TRANSITION_CREATED',
  TRANSACTION_UPDATED = 'TRANSACTION_UPDATED',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  WITHDRAWAL_INVALID = "WITHDRAWAL_INVALID",
  WITHDRAWAL_CREATED = "WITHDRAWAL_CREATED",
}
