export enum RoleEnum {
  DEACTIVATED_USER = 'AdminEnum',
  DATA_GET = 'DATA_GET',
  ROLE_LIST = 'ROLE_LIST',
  FAILED_TO_FETCH = 'FAILED_TO_FETCH',
  ROLE_GET = 'ROLE_GET',
  FAILED_TO_DELETE = 'FAILED_TO_DELETE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_CREATED = 'ROLE_CREATED',
}
