export enum ColourBettingEnum {
  REGISTERED_TYPE_NOT_MATCH_FOR_OTP = 'Register type not match for otp',
  FAILED_TO_CREATE = 'FAILED_TO_CREATE',
  COLOR_BET_CRATED = 'COLOR_BET_CRATED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  VALID_BET_AMOUNT = 'VALID_BET_AMOUNT',
  FAILED_TO_FETCH = 'FAILED_TO_FETCH',
  GAME_TYPE_REQUIRED = 'GAME_TYPE_REQUIRED',
  COLOR_RESULT = 'COLOR_RESULT',
  NUMBER_RESULT = 'NUMBER_RESULT',
  WINNER_DECLARE_MANUAL = 'WINNER_DECLARE_MANUAL',
  TYPE_REQUIRED = 'TYPE_REQUIRED',
  COLOR_USER_LIST = "COLOR_USER_LIST",
  DATA_NOT_FOUND = "DATA_NOT_FOUND",
  COLOR_WINNER = "COLOR_WINNER"
}
