export enum GameEnum {
  REGISTERED_TYPE_NOT_MATCH_FOR_OTP = 'Register type not match for otp',
  GAME_GET_ALL = 'GAME_GET_ALL',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  GAME_RULES_NOT_FOUND = 'GAME_RULES_NOT_FOUND',
  GAME_RULES_GET = 'GAME_RULES_GET',
  GAME_TIME_GET = 'GAME_TIME_GET',
  GAME_TIME_NOT_FOUND = 'GAME_TIME_NOT_FOUND',
}
