export enum PermissionEnum {
  PERMISSION_LIST_NOT_FOUND = 'PERMISSION_LIST_NOT_FOUND',
  PERMISSION_FETCHED = 'PERMISSION_FETCHED',
  PERMISSION_GET = 'PERMISSION_GET',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PARTNER_DELETED = 'PARTNER_DELETED',
  PARTNER_NOT_DELETED = 'PARTNER_NOT_DELETED',
  PERMISSION_UPDATED = 'PERMISSION_UPDATED',
  PERMISSION_CREATED = 'PERMISSION_CREATED',
  PERMISSION_NOT_CREATED = 'PERMISSION_NOT_CREATED',
  PERMISSION_DEACTIVE = 'PERMISSION_DEACTIVE',
  PERMISSION_ACTIVE = 'PERMISSION_ACTIVE',
}
